import { chrisPaint, artYellow, artStorm, artBlue } from '../../images/index'

export const data = [
    {
        id: 1,
        title: 'Storm',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artStorm,
        description: 'Something about the artwork, etc.',
        tag: 'new',
        size: '24X36',
        sold: true,
    },
    {
        id: 2,
        title: 'Silver Tatch',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artBlue,
        description: 'Something about the artwork, etc.',
        tag: 'featured',
        size: '24X36',
        sold: true,
    },
    {
        id: 3,
        title: 'Silver Tatch',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artBlue,
        description: 'Something about the artwork, etc.',
        tag: 'new',
        size: '24X36',
        sold: true,
    },
    {
        id: 4,
        title: 'New Era',
        date: 2021,
        medium: 'Oil on Canvas',
        image: chrisPaint,
        description: 'Something about the artwork, etc.',
        tag: 'all',
        size: '24X36',
        sold: true,
    },
    {
        id: 5,
        title: 'Maxi',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artYellow,
        description: 'Something about the artwork, etc.',
        tag: 'new',
        size: '24X36',
        sold: false,
    },
    {
        id: 6,
        title: 'Maxi',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artYellow,
        description: 'Something about the artwork, etc.',
        tag: 'all',
        size: '24X36',
        sold: true,
    },
    {
        id: 7,
        title: 'Storm',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artStorm,
        description: 'Something about the artwork, etc.',
        tag: 'new',
        size: '24X36',
        sold: true,
    },
    {
        id: 8,
        title: 'Silver Tatch',
        date: 2021,
        medium: 'Oil on Canvas',
        image: artBlue,
        description: 'Something about the artwork, etc.',
        tag: 'new',
        size: '24X36',
        sold: true,
    },

]