import ADrift from './Collections/fishing-catboats/bc-adrift1.jpg'
import ADrift2 from './Collections/fishing-catboats/bc-adrift2.jpg'
import BarkersBarracuda from './Collections/fishing-catboats/bc-barkersbarracuda.jpg'
import Catboys from './Collections/fishing-catboats/bc-catboys.jpg'
import CatboysSunset from './Collections/fishing-catboats/bc-catboyssunset.jpg'
import CatchingSprats from './Collections/fishing-catboats/bc-catchingsprats.jpg'
import FishpotTiems from './Collections/fishing-catboats/bc-fishpottimes.jpg'
import FishWithTheFlow from './Collections/fishing-catboats/bc-fishwiththeflow.jpg'
import LineFishing from './Collections/fishing-catboats/bc-linefishing.jpg'
import LineFishing2 from './Collections/fishing-catboats/bc-linefishing2.jpg'
import NevilleScott from './Collections/fishing-catboats/bc-nevillescott.jpg'
import NoBounderies from './Collections/fishing-catboats/bc-nobounderies.jpg'
import SaltwaterCowboys from './Collections/fishing-catboats/bc-saltwatercowboys.jpg'
import Saltwaters from './Collections/fishing-catboats/bc-saltwaters.jpg'
import Stryker from './Collections/fishing-catboats/bc-stryker.jpg'
import ThreeBoats from './Collections/fishing-catboats/bc-threeboats.jpg'
import TurtleCrawl from './Collections/fishing-catboats/bc-turtlecrawl.jpg'
import TurtleCrawl2 from './Collections/fishing-catboats/bc-turtlecrawl3.jpg'
import YellowTail from './Collections/fishing-catboats/bc-yellowtail.jpg'

export { ADrift, ADrift2, BarkersBarracuda, Catboys, CatboysSunset, CatchingSprats, FishpotTiems, FishWithTheFlow, LineFishing, LineFishing2, NevilleScott, NoBounderies, SaltwaterCowboys, Saltwaters, Stryker, ThreeBoats, TurtleCrawl, TurtleCrawl2, YellowTail }

