import ccIcon from './All/cc-icon.svg'
import chrisPainting from './All/chris-painting-web.jpg'
import ccLogo from './All/CC LOGO-08.svg'
import accIcon from './All/acc-icon.svg'
import chrisPaint from './All/chris-painting-web.jpg'
import artStorm from './All/cc-red-storm.jpg'
import artBlue from './All/cc-deep-blue.jpeg'
import artYellow from './All/cc-yellow-tatch.jpeg'
import ccLogoDark from './All/CC LOGO-02.svg'
import ccLogoWhite from './All/cc-logo-white.svg'
import accIconChris from './All/accicon-chris.svg'
import collFishing from './Collections/ccFishing.jpg'
import collAbstract from './Collections/collAbstract.jpg'
import collCatboats from './Collections/collCatboats.jpg'
import collCaymanian from './Collections/collCaymanians.jpg'
import collLiquid from './Collections/collLiquid.jpg'
import collWoman from './Collections/collWoman.jpg'
import chrisBw from './All/chris-bw.png'
import patternInt from './All/interlaced.png'
import cc1 from './All/cc1.jpg'
import cc2 from './All/cc2.jpg'
import cc3 from './All/cc3.jpg'
import beachWaves from './All/beachbeach.jpg'

export { ccIcon, chrisPainting, ccLogo, accIcon, chrisPaint, artStorm, artBlue, artYellow, ccLogoDark, ccLogoWhite, accIconChris, collFishing, collAbstract, collCatboats, collCaymanian, collLiquid, collWoman, chrisBw, patternInt,cc1, cc2, cc3, beachWaves }