import Navbar from './Navbar.jsx'
import Hero from './Hero.jsx'
import Carousel from './Carousel'
import Featured from './Featured'
import Contact from './Contact'
import Footer from './Footer'
import AllFeatured from './AllFeatured'
import Gallery from './Gallery'
import Gallery2 from './Gallery2'
import LandingPage from './LandingPage.jsx'
import Navb from './Navb.jsx'
import Cta from './Cta'
import Collections from './Collections.jsx'
import About from './About'

export  { Navbar, Hero, Carousel, Featured, Contact, Footer, AllFeatured, Gallery, Gallery2, LandingPage, Navb, Cta, Collections, About  }